import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import 'react-toastify/ReactToastify.css'
import { ThemeProvider } from '@/components/themeProvider'
import { FilesStoreProvider } from '@/providers/filesProvider'
import NavBar from '@/components/bar/navBar'
import { cn } from '@/lib/utils'
import { OptionsStoreProvider } from '@/providers/optionsProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={cn(inter.className, 'md:px-16 min-h-screen w-screen')}>
        <FilesStoreProvider>
          <OptionsStoreProvider>
            <ThemeProvider
              attribute='class'
              defaultTheme='system'
            >
              <NavBar />
              {children}
            </ThemeProvider>
          </OptionsStoreProvider>
        </FilesStoreProvider>
      </body>
    </html>
  )
}
