import NavBar from '@/components/bar/NavBar'
import { ThemeProvider } from '@/components/themeProvider'
import { Localforage } from '@/lib/localforage'
import { cn } from '@/lib/utils'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/ReactToastify.css'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={cn(inter.className, 'flex md:px-16 min-h-[100dvh] w-screen')}>
        <ThemeProvider
          attribute='class'
          defaultTheme='system'
        >
          <Localforage>
            <NavBar />
            <ToastContainer />
            {children}
          </Localforage>
        </ThemeProvider>
      </body>
    </html>
  )
}
